# Generated by Django 5.1.1 on 2024-10-02 07:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsacounter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='progress',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 2, 7, 56, 55, 559744, tzinfo=datetime.timezone.utc)),
        ),
    ]
