# Generated by Django 5.1.1 on 2024-10-02 18:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsacounter', '0003_alter_progress_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progress',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 2, 18, 2, 17, 113563, tzinfo=datetime.timezone.utc)),
        ),
    ]
