# Generated by Django 5.1.1 on 2024-10-03 15:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsacounter', '0004_alter_progress_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='progress',
            name='submittime',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 3, 15, 30, 36, 127135, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='progress',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 3, 15, 30, 36, 127135, tzinfo=datetime.timezone.utc)),
        ),
    ]
