# Generated by Django 5.1.1 on 2024-10-03 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsacounter', '0005_progress_submittime_alter_progress_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progress',
            name='date',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='progress',
            name='submittime',
            field=models.CharField(max_length=20),
        ),
    ]
