# Generated by Django 5.1.1 on 2024-10-03 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsacounter', '0006_alter_progress_date_alter_progress_submittime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progress',
            name='username',
            field=models.CharField(max_length=20),
        ),
    ]
