# Generated by Django 5.1.1 on 2024-10-10 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsacounter', '0010_progress_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rooms',
            old_name='owner',
            new_name='teacherid',
        ),
        migrations.RemoveField(
            model_name='progress',
            name='username',
        ),
        migrations.AlterField(
            model_name='progress',
            name='date',
            field=models.DateField(),
        ),
    ]
