# Generated by Django 5.1.1 on 2024-10-10 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dsacounter', '0012_rename_uid_progress_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='teachername',
            new_name='username',
        ),
    ]
