# Generated by Django 5.1.1 on 2024-10-10 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsacounter', '0013_rename_teachername_teacher_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='username',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
