# Generated by Django 5.1.1 on 2024-10-10 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dsacounter', '0014_teacher_last_login_alter_teacher_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='username',
            new_name='teachername',
        ),
    ]
