# Generated by Django 5.1.1 on 2024-10-10 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsacounter', '0016_alter_rooms_teacherid_rooms_roomname_delete_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='description',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
