# Generated by Django 5.1.1 on 2024-10-11 02:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsacounter', '0019_alter_studying_room_alter_studying_student'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='students',
            field=models.ManyToManyField(related_name='studying_rooms', through='dsacounter.studying', to=settings.AUTH_USER_MODEL),
        ),
    ]
