# Generated by Django 5.1.1 on 2024-11-13 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsacounter', '0021_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='progress',
            name='score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
